// export const slPercentSelections = [
//   { value: 0.05, label: '5%' },
//   { value: 0.1, label: '10%' },
//   { value: 0.25, label: '25%' },
//   { value: 0.5, label: '50%' },
//   { value: 0.75, label: '75%' },
// ];

// export const tpPercentSelections = [
//   { value: 0.1, label: '10%' },
//   { value: 0.25, label: '25%' },
//   { value: 0.5, label: '50%' },
//   { value: 1, label: '100%' },
//   { value: 1.5, label: '150%' },
// ];

// export const qtyPercentSelections = [
//   { value: 0.1, label: '10%' },
//   { value: 0.25, label: '25%' },
//   { value: 0.5, label: '50%' },
//   { value: 0.75, label: '75%' },
//   { value: 1, label: '100%' },
// ];

export const qtyPercentSelectionSliders = {
  0: '0%',
  0.25: '25%',
  0.5: '50%',
  0.75: '75%',
  1: '100%',
};

export const LANGUAGES = {
  ZH_CN: 'zh-CN',
  EN: 'en-US',
  ZH_TW: 'zh-TW',
  KO_KR: 'ko-KR',
  VI_VN: 'vi-VN',
  ID_ID: 'id-ID',
  ES_ES: 'es-ES',
  RU_RU: 'ru-RU',
  PT_PT: 'pt-PT',
  AR_SA: 'ar-SA',
  DE_DE: 'de-DE',
  FR_FR: 'fr-FR',
  JA_JP: 'ja-JP',
  TH_TH: 'th-TH',
  PT_BR: 'pt-BR',
  TR_TR: 'tr-TR',
  ZH_MY: 'zh-MY',
  UK_UA: 'uk-UA',
  KK_KZ: 'kk-KZ',
  HI_IN: 'hi-IN',
  FIL_PH: 'fil-PH',
  UZ_UZ: 'uz-UZ',
  ES_LA: 'es-LA',
  ES_419: 'es-419',
  ES_MX: 'es-MX',
  ES_AR: 'es-AR',
  PL_PL: 'pl-PL',
  AZ_AZ: 'az-AZ',
  SI_LK: 'si-LK',
  SK_SK: 'sk-SK',
  SL_SI: 'sl-SI',
  LO_LA: 'lo-LA',
  LV_LV: 'lv-LV',
  HU_HU: 'hu-HU',
  EL_GR: 'el-GR',
  CS_CZ: 'cs-CZ',
  BG_BG: 'bg-BG',
  SV_SE: 'sv-SE',
  DA_DK: 'da-DK',
  RO_RO: 'ro-RO',
  IT_IT: 'it-IT',
};

export const languageSelections = [
  { value: LANGUAGES.ZH_CN, label: '中文简体' },
  { value: LANGUAGES.EN, label: 'English' },
  { value: LANGUAGES.ZH_TW, label: '中文繁體' },
  { value: LANGUAGES.ZH_MY, label: '中文 (马来西亚)' },
  { value: LANGUAGES.KO_KR, label: '한국어' },
  { value: LANGUAGES.JA_JP, label: '日本語' },
  { value: LANGUAGES.VI_VN, label: 'Tiếng Việt' },
  { value: LANGUAGES.ID_ID, label: 'Bahasa Indonesia' },
  { value: LANGUAGES.TH_TH, label: 'ไทย' },
  { value: LANGUAGES.FIL_PH, label: 'Filipino' },
  { value: LANGUAGES.HI_IN, label: 'हिन्दी' },
  { value: LANGUAGES.ES_ES, label: 'Español (España)' },
  { value: LANGUAGES.ES_LA, label: 'Español (Latinoamérica)' },
  { value: LANGUAGES.ES_419, label: 'Español (Internacional)' },
  { value: LANGUAGES.ES_MX, label: 'Español (México)' },
  { value: LANGUAGES.ES_AR, label: 'Español (Argentina)' },
  { value: LANGUAGES.PT_PT, label: 'Português (Portugal)' },
  { value: LANGUAGES.PT_BR, label: 'Português (Brasil)' },
  { value: LANGUAGES.FR_FR, label: 'Français' },
  { value: LANGUAGES.DE_DE, label: 'Deutsch' },
  { value: LANGUAGES.IT_IT, label: 'Italiano' },
  { value: LANGUAGES.RU_RU, label: 'Русский' },
  { value: LANGUAGES.UK_UA, label: 'Українська' },
  { value: LANGUAGES.PL_PL, label: 'Polski' },
  { value: LANGUAGES.CS_CZ, label: 'Čeština' },
  { value: LANGUAGES.SK_SK, label: 'Slovenčina' },
  { value: LANGUAGES.SL_SI, label: 'Slovenščina' },
  { value: LANGUAGES.HU_HU, label: 'Magyar' },
  { value: LANGUAGES.RO_RO, label: 'Română' },
  { value: LANGUAGES.BG_BG, label: 'Български' },
  { value: LANGUAGES.EL_GR, label: 'Ελληνικά' },
  { value: LANGUAGES.SV_SE, label: 'Svenska' },
  { value: LANGUAGES.DA_DK, label: 'Dansk' },
  { value: LANGUAGES.TR_TR, label: 'Türkçe' },
  { value: LANGUAGES.AZ_AZ, label: 'Azərbaycan' },
  { value: LANGUAGES.KK_KZ, label: 'қазақша' },
  { value: LANGUAGES.UZ_UZ, label: 'Oʻzbekcha' },
  { value: LANGUAGES.LV_LV, label: 'Latviešu' },
  { value: LANGUAGES.LO_LA, label: 'ລາວ' },
  { value: LANGUAGES.SI_LK, label: 'සිංහල' },
  { value: LANGUAGES.AR_SA, label: 'العربية' },
];
