module.exports = {
  'publicKeyPEM-test': `
    -----BEGIN PRIVATE KEY-----
  MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDeHcXEpvRxr1WAda
  3vI6X2buSgpBiKrcrGZSQjxvt1igCgYIKoZIzj0DAQehRANCAASF7k7ae9E38aLk
  wVs58S42ZAFSQ3IBEmb0Ajvka+YyRJqQcWwutCwX47V8KG1eySXENbwnV0J+KJje
  KCAptqPG
  -----END PRIVATE KEY-----`,
  
  'publicKeyPEM-testnet': `
    -----BEGIN PRIVATE KEY-----
  MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDeHcXEpvRxr1WAda
  3vI6X2buSgpBiKrcrGZSQjxvt1igCgYIKoZIzj0DAQehRANCAASF7k7ae9E38aLk
  wVs58S42ZAFSQ3IBEmb0Ajvka+YyRJqQcWwutCwX47V8KG1eySXENbwnV0J+KJje
  KCAptqPG
  -----END PRIVATE KEY-----`,

  'publicKeyPEM-prod': `
    ------BEGIN PRIVATE KEY-----
  MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgDeHcXEpvRxr1WAda
  3vI6X2buSgpBiKrcrGZSQjxvt1igCgYIKoZIzj0DAQehRANCAASF7k7ae9E38aLk
  wVs58S42ZAFSQ3IBEmb0Ajvka+YyRJqQcWwutCwX47V8KG1eySXENbwnV0J+KJje
  KCAptqPG
  -----END PRIVATE KEY-----`
};
