map $http_accept_language $lang {
    default en-US;
    ~id id-ID;
    ~th th-TH;
    ~fr fr-FR;
    ~pt-BR pt-BR;
    ~pt-PT pt-PT;
    ~tr tr-TR;
    ~es es-ES;
    ~ja ja-JP;
    ~ru ru-RU;
    ~vi vi-VN;
    ~zh-CN zh-MY;
    ~zh-MY zh-MY;
    ~zh-TW zh-TW;
    ~fil fil-PH;
    ~kk kk-KZ;
    ~uk uk-UA;
    ~hi hi-IN;
    ~es-ES es-ES;
    ~es-419 es-419;
    ~es-MX es-MX;
    ~es-AR es-AR;
    ~ar-SA ar-SA;
}

map $status $cache_header {
    default "max-age=31536000";
    404     "no-store";
}
