import { handleX } from 'common/utils/order';
import { toNumberZero } from 'common/utils/utils';

export const order = (data = {}) => {
  const {
    side,
    symbol,
    orderId,
    orderType,
    timeInForce,
    reduceOnly,
    triggerBy,
    stopOrderType,
    expectedDirection,
    orderStatus,
    cxlRejReason,
    isWorking,
    type,
    tpTriggerBy,
    slTriggerBy,
    createType,
    cancelType,
    qtyX,
    leavesQtyX,
    cumQtyX,
    origQtyX,
    ...others
  } = data;
  return {
    ...others,
    symbol,
    tpTriggerBy,
    slTriggerBy,
    createType,
    cancelType,
    takeProfit: toNumberZero(data.takeProfit),
    stopLoss: toNumberZero(data.stopLoss),
    orderId,
    side,
    orderType,
    timeInForce,
    reduceOnly,
    stopOrderType,
    triggerBy,
    expectedDirection,
    basePrice: toNumberZero(data.basePrice),
    trailValue: toNumberZero(data.trailValue),
    triggerPrice: toNumberZero(data.triggerPrice),
    price: toNumberZero(data.price),
    qtyX: toNumberZero(qtyX),
    leavesQtyX: toNumberZero(leavesQtyX),
    cumQtyX: toNumberZero(cumQtyX),
    cumValueE8: toNumberZero(data.cumValueE8),
    // cumExecFee: toNumberZero(data.cumExecFeeE8 / 1e8),
    orderStatus,
    cxlRejReason,
    lastExecPrice: toNumberZero(data.lastExecPrice),
    createdAtE3: toNumberZero(data.createdAtE3),
    updatedAtE3: toNumberZero(data.updatedAtE3),
    origTriggerPrice: toNumberZero(data.origTriggerPrice),
    origPrice: toNumberZero(data.origPrice),
    origQtyX: toNumberZero(origQtyX),
    isWorking,
    type,

    qty: handleX(qtyX, symbol),
    leavesQty: handleX(leavesQtyX, symbol),
    cumQty: handleX(cumQtyX, symbol),
    origQty: handleX(origQtyX, symbol),
  };
};
