import { toNumberZero } from 'common/utils/utils';
import { handleX } from 'common/utils/order';

export const position = (data = {}) => {
  const {
    markPrice,
    liqPrice,
    bustPrice,
    takeProfit,
    stopLoss,
    trailingStop,
    activationPrice,
    closingPrice,
    entryPriceE8,
    extraAddedMarginE8,
    valueE8,
    positionBalanceE8,
    minPositionCostE8,
    unrealisedPnlByLpE8,
    occClosingFeeE8,
    leverageE2,
    closingQtyX,
    sizeX,
    tpFreeSizeX,
    slFreeSizeX,
    bv2cE8,
    sv2cE8,
    symbol,
    fqX,
    ...others
  } = data;

  return {
    ...others,
    symbol,
    markPrice: toNumberZero(markPrice),
    liqPrice: toNumberZero(liqPrice),
    bustPrice: toNumberZero(bustPrice),
    takeProfit: toNumberZero(takeProfit),
    stopLoss: toNumberZero(stopLoss),
    trailingStop: toNumberZero(trailingStop),
    activationPrice: toNumberZero(activationPrice),
    closingPrice: toNumberZero(closingPrice),
    entryPriceE8,
    entryPrice: toNumberZero(entryPriceE8 / 1e8),
    extraAddedMarginE8,
    extraAddedMargin: toNumberZero(extraAddedMarginE8 / 1e8),
    valueE8,
    value: toNumberZero(valueE8 / 1e8),
    positionBalanceE8,
    positionBalance: toNumberZero(positionBalanceE8 / 1e8),
    minPositionCostE8,
    minPositionCost: toNumberZero(minPositionCostE8 / 1e8),
    leverage: toNumberZero(leverageE2 / 1e2),
    leverageE2,
    bv2cE8,
    sv2cE8,
    bv2c: toNumberZero(bv2cE8 / 1e8),
    sv2c: toNumberZero(sv2cE8 / 1e8),
    occClosingFeeE8,
    occClosingFee: toNumberZero(occClosingFeeE8 / 1e8),
    fqX,
    closingQtyX,
    sizeX,
    tpFreeSizeX,
    slFreeSizeX,
    unrealisedPnlByLpE8,
    unrealisedPnlByLp: toNumberZero(unrealisedPnlByLpE8 / 1e8),
    // 仅供正向使用
    fq: handleX(fqX, symbol),
    closingQty: handleX(closingQtyX, symbol),
    size: handleX(sizeX, symbol),
    tpFreeSize: handleX(tpFreeSizeX, symbol),
    slFreeSize: handleX(slFreeSizeX, symbol),
  };
};
